apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agenticseek.fullname" . }}-backend
  labels:
    {{- include "agenticseek.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "agenticseek.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "agenticseek.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agenticseek.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.backend.targetPort }}
              protocol: TCP
          env:
            - name: SEARXNG_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-config
                  key: SEARXNG_BASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-config
                  key: REDIS_URL
            - name: DEPLOYMENT_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-config
                  key: DEPLOYMENT_MODE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-config
                  key: LOG_LEVEL
            {{- if .Values.secrets.openaiApiKey }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-secrets
                  key: OPENAI_API_KEY
                  optional: true
            {{- end }}
            {{- if .Values.secrets.deepseekApiKey }}
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-secrets
                  key: DEEPSEEK_API_KEY
                  optional: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ include "agenticseek.fullname" . }}-workspace-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenticseek.fullname" . }}-backend-service
  labels:
    {{- include "agenticseek.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "agenticseek.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
