apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agenticseek.fullname" . }}-searxng
  labels:
    {{- include "agenticseek.labels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
spec:
  replicas: {{ .Values.searxng.replicaCount }}
  selector:
    matchLabels:
      {{- include "agenticseek.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: searxng
  template:
    metadata:
      labels:
        {{- include "agenticseek.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: searxng
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agenticseek.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.searxng.podSecurityContext | nindent 8 }}
      containers:
        - name: searxng
          securityContext:
            {{- toYaml .Values.searxng.securityContext | nindent 12 }}
          image: "{{ .Values.searxng.image.repository }}:{{ .Values.searxng.image.tag }}"
          imagePullPolicy: {{ .Values.searxng.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.searxng.resources | nindent 12 }}
          env:
            - name: SEARXNG_BASE_URL
              value: {{ .Values.searxng.baseUrl | quote }}
            - name: SEARXNG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agenticseek.fullname" . }}-secret
                  key: searxng-secret-key
          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
              readOnly: true
      volumes:
        - name: searxng-config
          configMap:
            name: {{ include "agenticseek.fullname" . }}-configmap
            items:
              - key: searxng-settings
                path: settings.yml
      {{- with .Values.searxng.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searxng.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searxng.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenticseek.fullname" . }}-searxng
  labels:
    {{- include "agenticseek.labels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
spec:
  type: {{ .Values.searxng.service.type }}
  ports:
    - port: {{ .Values.searxng.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agenticseek.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
