apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenticseek.fullname" . }}-secret
  labels:
    {{- include "agenticseek.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.deepseekApiKey }}
  deepseek-api-key: {{ .Values.secrets.deepseekApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.searxngSecretKey }}
  searxng-secret-key: {{ .Values.secrets.searxngSecretKey | b64enc | quote }}
  {{- else }}
  searxng-secret-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  google-api-key: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.auth.enabled }}
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
